# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='example-url', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
